FORMAT: 1A
HOST: http://housedowning.me:8000/

# GOTapi

Simple API for navigating the GOT inspired imdb

## Group Person

Resources related to characters in the API.

A Person object has the following attributes:

+ Id
+ Person Id
+ First Name
+ Last Name
+ Titles
+ Actor
+ Status (alive or dead)
+ Cause of Death
+ Bio
+ Region From
+ Killer
+ Houses
+ Loyal To


## All People [/content/api/people/]

### View all people [GET]

+ Response 200 (application/json)

        [
            {
                "id": 69,
                "person_id": "bronn",
                "first_name": "Bronn",
                "last_name": null,
                "titles": "Ser, Commander of the City Watch (briefly) (former)",
                "actor": "Jerome Flynn",
                "status": "Alive",
                "cause_of_death": null,
                "bio":"...",
                "region_from": null,
                "killer": null,
                "houses": [],
                "loyal_to": [3],
                "castles_controlled": []
            },
            {
                "id": 66,
                "person_id": "drogo",
                "first_name": "Drogo",
                "last_name": null,
                "titles": "Khal",
                "actor": "Jason Momoa",
                "status": "Deceased",
                "cause_of_death": null,
                        "region_from": 13,
                "killer": null,
                "houses": [],
                "loyal_to": [],
                "castles_controlled": [28]
            }
        ]
        
## Person [/content/api/people/{person_id}]
### View a person [GET]
+ Parameters
    + person_id - simple identity string (lowercase name separated by an underscore)
+ Response 200 (application/json)

        [
            {
                "id":47,
                "person_id":"robert_baratheon",
                "first_name":"Robert",
                "last_name":"Baratheon",
                "titles": "King of the Andals and the First Men, Lord of the Seven Kingdoms, Protector of the Realm, Lord of Storm's End (former), Lord Paramount of the Stormlands (former)",
                "actor":"Mark Addy",
                "status":"Deceased",
                "cause_of_death":null,
                "bio":"...",
                "region_from": 2,
                "killer": null,
                "houses": [2],
                "loyal_to": []
            }
        ]

## Group Castles

A Castle has the following attributes:

+ Id
+ Castle Id
+ Name
+ Description
+ History
+ Region Name
+ Primary House
+ Primary Lord
+ Previous Houses
+ Previous Lords

## All Castles [/content/api/castles/]

### View all castles [GET]

+ Response 200 (application/json)

        [
            {
                "id": 21,
                "castle_id": "asshai",
                "name": "Asshai",
                "description": "...",
                "history": "...",
                "region_name": 13,
                "primary_house": null,
                "primary_lord": null,
                "previous_houses": [],
                "previous_lords": []
            },
            {
                "id": 33,
                "castle_id": "astapor",
                "name": "Astapor",
                "description": "...",
                "history": "...",
                "region_name": 13,
                "primary_house": 4,
                "primary_lord": 19,
                "previous_houses": [],
                "previous_lords": []
            }
        ]

## Castle [/content/api/castles/{castle_id}]

### View a castle [GET]
+ Parameters
    + castle_id - String of the castle name (lowercase with underscore separators)
    
+ Response 200 (application/json)

        [
            {
                "id": 1,
                "castle_id": "winterfell",
                "name": "Winterfell",
                "description": "...",
                "history":"...",
                "region_name": 1,
                "primary_house": 6,
                "primary_lord": 23,
                "previous_houses": [1],
                "previous_lords": []
            }
        ]

## Group Regions

A region has the following attributes:

+ Id
+ Region Id
+ Name
+ Description
+ History
+ Capitol Name
+ Ruling House
+ Ruling Lord
+ Other Castles
+ Previous Ruling Houses
+ Resident Houses

## All Regions [/content/api/regions/]

### View all regions [GET]
    
+ Response 200 (application/json)
    
        [
            {
                "id": 12,
                "region_id": "bear_island",
                "name": "Bear Island",
                "description": "...",
                "history":"...",
                "capital_name": null,
                "ruling_house": 6,
                "ruling_lord": 23,
                "other_castles": [],
                "previous_ruling_houses": [],
                "resident_houses": []
            },
            {   
                "id": 10,
                "region_id": "beyond_the_wall",
                "name": "Beyond the Wall",
                "capital_name": null,
                "ruling_house": null,
                "ruling_lord": 86,
                "other_castles": [],
                "previous_ruling_houses": [],
                "resident_houses": []
            }
        ]

## Region [/content/api/regions/{region_id}]

### View a region [GET]
+ Parameters
    + region_id - String of the region name (lowercase with underscore separators)
    
+ Response 200 (application/json)

        [
            {
                "id": 1,
                "region_id": "north",
                "name": "The North",
                "description":"...",
                "history":"...",
                "capital_name": 1,
                "ruling_house": 6,
                "ruling_lord": 23,
                "other_castles": [],
                "previous_ruling_houses": [],
                "resident_houses": []
            }
        ]

## Group Houses

A house has the following attributes:

+ Id
+ House_Id
+ Name
+ Words
+ Sigil
+ Description
+ Castles Controlled
+ Former Castles Controlled
+ Member

## All Houses [/content/api/houses/]

### View all houses [GET]
    
+ Response 200 (application/json)
    
        [
            {
                "id": 18,
                "house_id": "arryn",
                "name": "House Arryn",
                "words": "As High as Honor",
                "sigil": null,
                "description": "...",
                "castles_controlled": [6],
                "former_castles_controlled": [],
                "members": [42,40,41]
            },
            {   
                "id": 9,
                "house_id": "baelish",
                "name": "House Baelish",
                "words": null,
                "sigil": null,
                "description": "...",
                "castles_controlled": [16,6],
                "former_castles_controlled": [],
                "members": [40,46]
            }
        ]

## House [/content/api/houses/{house_id}]

### View a house [GET]
+ Parameters
    + house_id - String of the house name (lowercase with underscore separators)
    
+ Response 200 (application/json)

        [
            {
                "id": 2,
                "house_id": "baratheon",
                "name": "House Baratheon",
                "words": "Ours is the Fury",
                "sigil": null,
                "description":"...",
                "castles_controlled": [17,20,8,2],
                "former_castles_controlled": [],
                "members": [50,53,48,47,54,52,49,51,24]
            }
        ]





















