FORMAT: 1A
HOST: http://GOT.apiblueprint.org/

# GOTapi

Simple API for navigating the GOT inspired imdb

## Group Splash Page

# Splash Page [/]

Going to have links to characters in places that appear in the show. 

## Go to home page [GET]

+ Response 200 (application/json)

        {
            "Person_url": "/Person"
            "Castles_url": "/Castles"
            "Region_url": "/Regions"
        }

## Group Person

Resources related to character in the API.

## Person [/Person/{Person_id}]

A Person object has the following attributes:

+ First Name
+ Last Name
+ Actor Name
+ Title
+ House Name
+ Status
+ Bio
+ url

### View a Person in detail [GET]

+ Parameters
    + Person_id: Jon.Snow (required, string) - ID of the Person in the form first.last
+ Response 200 (application/json)

        {
            "First Name": "Jon",
            "Last Name": "Snow",
            "Actor Name": "Kit Harrington",
            "Title": "Lord Commander of the Night's Watch",
            "House Name": "Stark",
            "Status": "Dead",
            "Bio": "Sample bio",
            "url": "/Character/Jon.Snow"
        }



### Create a New Person [POST]

You may create your own Person using this action. It takes a JSON
object containing a Person and their attributes.

+ Person (string) - The Person


+ Request (application/json)

        {
            "Person": "Jon.Snow"
        }

+ Response 201 (application/json)

    + Headers

            Location: /Person/Jon.Snow

    + Body

            {
                "First Name": "Jon",
                "Last Name": "Snow",
                "Actor Name": "Kit Harrington",
                "Title": "Lord Commander of the Night's Watch",
                "House Name": "Stark",
                "Status": "Dead",
                "Bio": "Sample bio",
                "url": "/Character/Jon.Snow"
            }

## Group Castle

## Castle [/Castle/{Castle_id}]

A Castle has the following attributes:
+ Name
+ Location
+ Ruling Family
+ Description
+ History
+ url

### View a castle in detail [GET]

+ Parameters 
    + Castle_id : "Winterfell" (required, string) 

+ Response 200 (application/json)

        {
            "Name": "Winterfell",
            "Location": "The North",
            "Ruling Family": "The Starks",
            "Description": "Sample description",
            "History": "Sample history",
            "url": "/Castle/Winterfell"
        }



## Group Region

## Region [/Region/{Region_id}]

A region has the following attributes:
+ Region Name
+ Capitol
+ Ruling Family
+ Description
+ History
+ url

### View a region in detail [GET]

+ Parameters
    + Region_id : "The.North" (required, string)
    
+ Response 200 (application/json)
    
        {
            "Region Name": "The North",
            "Capitol": "Winterfell",
            "Ruling Family": "The Starks",
            "Description": "Sample description",
            "History": "Sample history",
            "url": "/Region/The.North"
        }
























